### ISSUE TITLE
Union 2 querys from differents models

### ISSUE THREAD

**Issue by ovninosa** [LiveControl/EloquentDataTable#4]
Hello,

There is any way to mix two querys from different models to return on the EloquentDataTable?

For example (and better explanation):

The 2 models are linked to the user between many to many relationship.

1) Model BeverageBrand (id, name) (user->beverageBrands())
2) Model BeverageBrandSuggestion (id, name) (user->beverageBrandsSuggestions())

I need to return the 2 models on the same datatable to give a transparent functionality to the end user.

This is can be done by EloquentDataTable?

Thanks in advance.

PS: Sorry if this is not correct as a Issue.

**Comment by jeffreydevreede** [comment]
I've added an example to the readme, this should show you how to work with relations. Hopefully this will help you solve your problem.

**Comment by ovninosa** [comment]
jeffrey thanks for your support.

But the example does not fit with my requirement. Sorry maybe my explanation is too simple and too vague.

I need something like this (just look the idea, of course this code doesn't work)

```
public function datatable()
{
    $beverageBrand = new BeverageBrand();
    $dataTable1 = new DataTable(
        $beverageBrand
        ['id', 'name']
    );

    $beverageBrandSuggestion  = new BeverageBrandSuggestion();
    $dataTable2 = new DataTable(
        $beverageBrandSuggestion
        ['id', 'name']
    );  

    $dataTable1->setFormatRowFunction(function ($beverage) {
        return [
            '<a href="/beverage/'.$beverage->id.'">'.$beverage->name.'</a>',
            $beverage->name,
        ];
    });

    $dataTable2->setFormatRowFunction(function ($beverage) {
        return [
            '<a href="/beverageSuggestion/'.$beverage->id.'">'.$beverage->name.'</a>',
            $beverage->name,
        ];
    }); 

    $dataTable = $dataTable1->union($dataTable2);

    return $dataTable->make();
}
```

There is any chance to make something like this??

**Comment by jeffreydevreede** [comment]
You should be able to do something like that but with a different approach, take a look at the union function (http://laravel.com/docs/5.0/queries#unions). I haven't tested this out myself, but using unions should be no problem.

**Comment by ovninosa** [comment]
Jeffrey, thanks for your time. 

Can you make a simple example?

I try to figure it out, but I can't do it.
If I do the next the compiler thrown an exception:

```
    $beverages = DB::table('beverage');
    $dataTable = new DataTable(
        $beverages,
        ['name', 'number']
    );

    $dataTable->setFormatRowFunction(function ($beverage) {
        $row = [];
        $row[] = $beverage->name;
        $row[] = $beverage->number;
        return $row;
    });

    return response()->json($dataTable->make());
```

FatalErrorException in DataTable.php line 51: Class 'LiveControl\EloquentDataTable\Exception' not found
