### ISSUE TITLE
Searching is Not working, 

### ISSUE THREAD

**Issue by kambona** [LiveControl/EloquentDataTable#5]
Searching is Not working, error unknown column primary key whick converted to camel case, i.e. if table name is "AssessmentTools" it generate id wirh a name "AssessmentToolsID" that is where the problem is. please help.

$category =  new AssessmentToolsCategory();
        $dataTable = new DataTable(
            $category->rightjoin('assessment_tools','assessment_tools_categories.id','=','assessment_tools_category_id'),['assessment_tools_categories.id','name','filename','filesize','assessment_tools.id']
        );

**Comment by jeffreydevreede** [comment]
This issue is now solved, @kambona sorry for the late response.
