### ISSUE TITLE
Relations/with gives me always null values ...

### ISSUE THREAD

**Issue by nickurt** [LiveControl/EloquentDataTable#8]
When I try this plugin with a relationship, it will be always null;

```
$payments = new Payments();
$dataTable = new \LiveControl\EloquentDataTable\DataTable($payments->with('user'), ['id', 'subject']);

$dataTable->setFormatRowFunction(function ($payment) {
    dd($payment->user); // null
});
```

I'm using Laravel 5.1 LTS.

Any idea?

**Comment by jeffreydevreede** [comment]
Sorry for the late response, this plugin isn't maintained anymore. However in case you are still using it. If you add the user_id column as one of the fields to be selected you should be able to do `$payment->user`.
